name:                hake
version:             0.1.0.0

default-extensions:
  - OverloadedStrings
  - LambdaCase
  - NamedFieldPuns
  - FlexibleContexts

ghc-options: 
  - -Wall
  - -Werror=incomplete-patterns

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - hint
  - mtl
  - text

library:
  source-dirs: src

executables:
  hake:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - hake
    ghc-options: 
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2

tests:
  hake-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hake
    - aeson
    - hspec